/* eslint-disable max-len */

import { Languages, ProjectData, RepoData } from './models';

/* eslint-disable @typescript-eslint/naming-convention */
export class GitHubConstants {
  public static readonly allGithubBackupData: RepoData[] = [
    {
      description: 'Android App for home brewing recipes and calculations',
      language: 'Java',
      name: 'BrewBuddy-Android',
      url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-Android',
      value: 17960,
    },
    {
      description: 'iOS app for home brewing recipes and calculations',
      language: 'Swift',
      name: 'BrewBuddy-iOS',
      url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-iOS',
      value: 15522,
    },
    {
      description: 'Web application to serve club content on displays throughout the club',
      language: 'TypeScript',
      name: 'ColYCBillboard.com',
      url: 'https://api.github.com/repos/TaylorShane/ColYCBillboard.com',
      value: 100774,
    },
    {
      description: 'Weather app for ColYC screens',
      language: 'TypeScript',
      name: 'ColYCWeather.com',
      url: 'https://api.github.com/repos/TaylorShane/ColYCWeather.com',
      value: 777,
    },
    {
      description: 'Educational Android app created to help middle school students learn geometry.',
      language: 'Java',
      name: 'Graphy',
      url: 'https://api.github.com/repos/TaylorShane/Graphy',
      value: 8925,
    },
    {
      description: 'A 3NF relational database.',
      language: 'PLSQL',
      name: 'Modern-Database-Management',
      url: 'https://api.github.com/repos/TaylorShane/Modern-Database-Management',
      value: 381,
    },
    {
      description: 'Userspace Raspberry Pi PWM library for WS281X LEDs',
      language: 'C',
      name: 'rpi_ws281x',
      url: 'https://api.github.com/repos/TaylorShane/rpi_ws281x',
      value: 408,
    },
    {
      description: 'Angular Developer profile website',
      language: 'TypeScript',
      name: 'shanetaylor.dev',
      url: 'https://api.github.com/repos/TaylorShane/shanetaylor.dev',
      value: 245413,
    },
    {
      description: 'A WPF C# app that tracks caloric intake and exercise management.',
      language: 'C#',
      name: 'Spotter',
      url: 'https://api.github.com/repos/TaylorShane/Spotter',
      value: 20706,
    },
    {
      description: 'Config files for my GitHub profile.',
      language: null,
      name: 'TaylorShane',
      url: 'https://api.github.com/repos/TaylorShane/TaylorShane',
      value: 2,
    },
  ];

  public static readonly allGithubBackupDataRaw: any[] = [
    {
      id: 91990149,
      node_id: 'MDEwOlJlcG9zaXRvcnk5MTk5MDE0OQ==',
      name: 'BrewBuddy-Android',
      full_name: 'TaylorShane/BrewBuddy-Android',
      private: false,
      owner: {
        login: 'TaylorShane',
        id: 26348898,
        node_id: 'MDQ6VXNlcjI2MzQ4ODk4',
        avatar_url: 'https://avatars.githubusercontent.com/u/26348898?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/TaylorShane',
        html_url: 'https://github.com/TaylorShane',
        followers_url: 'https://api.github.com/users/TaylorShane/followers',
        following_url: 'https://api.github.com/users/TaylorShane/following{/other_user}',
        gists_url: 'https://api.github.com/users/TaylorShane/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/TaylorShane/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/TaylorShane/subscriptions',
        organizations_url: 'https://api.github.com/users/TaylorShane/orgs',
        repos_url: 'https://api.github.com/users/TaylorShane/repos',
        events_url: 'https://api.github.com/users/TaylorShane/events{/privacy}',
        received_events_url: 'https://api.github.com/users/TaylorShane/received_events',
        type: 'User',
        site_admin: false,
      },
      html_url: 'https://github.com/TaylorShane/BrewBuddy-Android',
      description: 'Android app for home brewing recipes and calculations',
      fork: false,
      url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-Android',
      forks_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-Android/forks',
      keys_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-Android/keys{/key_id}',
      collaborators_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-Android/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-Android/teams',
      hooks_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-Android/hooks',
      issue_events_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-Android/issues/events{/number}',
      events_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-Android/events',
      assignees_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-Android/assignees{/user}',
      branches_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-Android/branches{/branch}',
      tags_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-Android/tags',
      blobs_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-Android/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-Android/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-Android/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-Android/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-Android/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-Android/languages',
      stargazers_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-Android/stargazers',
      contributors_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-Android/contributors',
      subscribers_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-Android/subscribers',
      subscription_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-Android/subscription',
      commits_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-Android/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-Android/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-Android/comments{/number}',
      issue_comment_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-Android/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-Android/contents/{+path}',
      compare_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-Android/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-Android/merges',
      archive_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-Android/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-Android/downloads',
      issues_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-Android/issues{/number}',
      pulls_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-Android/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-Android/milestones{/number}',
      notifications_url:
        'https://api.github.com/repos/TaylorShane/BrewBuddy-Android/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-Android/labels{/name}',
      releases_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-Android/releases{/id}',
      deployments_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-Android/deployments',
      created_at: '2017-05-21T21:58:51Z',
      updated_at: '2021-01-01T19:05:28Z',
      pushed_at: '2017-05-21T21:59:30Z',
      git_url: 'git://github.com/TaylorShane/BrewBuddy-Android.git',
      ssh_url: 'git@github.com:TaylorShane/BrewBuddy-Android.git',
      clone_url: 'https://github.com/TaylorShane/BrewBuddy-Android.git',
      svn_url: 'https://github.com/TaylorShane/BrewBuddy-Android',
      homepage: '',
      size: 17960,
      stargazers_count: 0,
      watchers_count: 0,
      language: 'Java',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      has_discussions: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: null,
      allow_forking: true,
      is_template: false,
      web_commit_signoff_required: false,
      topics: ['android', 'beer', 'homebrew', 'recipes'],
      visibility: 'public',
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'master',
    },
    {
      id: 107330759,
      node_id: 'MDEwOlJlcG9zaXRvcnkxMDczMzA3NTk=',
      name: 'BrewBuddy-iOS',
      full_name: 'TaylorShane/BrewBuddy-iOS',
      private: false,
      owner: {
        login: 'TaylorShane',
        id: 26348898,
        node_id: 'MDQ6VXNlcjI2MzQ4ODk4',
        avatar_url: 'https://avatars.githubusercontent.com/u/26348898?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/TaylorShane',
        html_url: 'https://github.com/TaylorShane',
        followers_url: 'https://api.github.com/users/TaylorShane/followers',
        following_url: 'https://api.github.com/users/TaylorShane/following{/other_user}',
        gists_url: 'https://api.github.com/users/TaylorShane/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/TaylorShane/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/TaylorShane/subscriptions',
        organizations_url: 'https://api.github.com/users/TaylorShane/orgs',
        repos_url: 'https://api.github.com/users/TaylorShane/repos',
        events_url: 'https://api.github.com/users/TaylorShane/events{/privacy}',
        received_events_url: 'https://api.github.com/users/TaylorShane/received_events',
        type: 'User',
        site_admin: false,
      },
      html_url: 'https://github.com/TaylorShane/BrewBuddy-iOS',
      description: 'iOS app for home brewing recipes and calculations',
      fork: false,
      url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-iOS',
      forks_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-iOS/forks',
      keys_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-iOS/keys{/key_id}',
      collaborators_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-iOS/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-iOS/teams',
      hooks_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-iOS/hooks',
      issue_events_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-iOS/issues/events{/number}',
      events_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-iOS/events',
      assignees_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-iOS/assignees{/user}',
      branches_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-iOS/branches{/branch}',
      tags_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-iOS/tags',
      blobs_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-iOS/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-iOS/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-iOS/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-iOS/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-iOS/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-iOS/languages',
      stargazers_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-iOS/stargazers',
      contributors_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-iOS/contributors',
      subscribers_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-iOS/subscribers',
      subscription_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-iOS/subscription',
      commits_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-iOS/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-iOS/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-iOS/comments{/number}',
      issue_comment_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-iOS/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-iOS/contents/{+path}',
      compare_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-iOS/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-iOS/merges',
      archive_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-iOS/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-iOS/downloads',
      issues_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-iOS/issues{/number}',
      pulls_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-iOS/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-iOS/milestones{/number}',
      notifications_url:
        'https://api.github.com/repos/TaylorShane/BrewBuddy-iOS/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-iOS/labels{/name}',
      releases_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-iOS/releases{/id}',
      deployments_url: 'https://api.github.com/repos/TaylorShane/BrewBuddy-iOS/deployments',
      created_at: '2017-10-17T22:26:29Z',
      updated_at: '2021-01-01T19:07:01Z',
      pushed_at: '2020-12-02T00:52:17Z',
      git_url: 'git://github.com/TaylorShane/BrewBuddy-iOS.git',
      ssh_url: 'git@github.com:TaylorShane/BrewBuddy-iOS.git',
      clone_url: 'https://github.com/TaylorShane/BrewBuddy-iOS.git',
      svn_url: 'https://github.com/TaylorShane/BrewBuddy-iOS',
      homepage: '',
      size: 15522,
      stargazers_count: 0,
      watchers_count: 0,
      language: 'Swift',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      has_discussions: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: null,
      allow_forking: true,
      is_template: false,
      web_commit_signoff_required: false,
      topics: ['beer', 'ios', 'ios-swift'],
      visibility: 'public',
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'master',
    },
    {
      id: 425563539,
      node_id: 'R_kgDOGV2Vkw',
      name: 'ColYCBillboard.com',
      full_name: 'TaylorShane/ColYCBillboard.com',
      private: false,
      owner: {
        login: 'TaylorShane',
        id: 26348898,
        node_id: 'MDQ6VXNlcjI2MzQ4ODk4',
        avatar_url: 'https://avatars.githubusercontent.com/u/26348898?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/TaylorShane',
        html_url: 'https://github.com/TaylorShane',
        followers_url: 'https://api.github.com/users/TaylorShane/followers',
        following_url: 'https://api.github.com/users/TaylorShane/following{/other_user}',
        gists_url: 'https://api.github.com/users/TaylorShane/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/TaylorShane/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/TaylorShane/subscriptions',
        organizations_url: 'https://api.github.com/users/TaylorShane/orgs',
        repos_url: 'https://api.github.com/users/TaylorShane/repos',
        events_url: 'https://api.github.com/users/TaylorShane/events{/privacy}',
        received_events_url: 'https://api.github.com/users/TaylorShane/received_events',
        type: 'User',
        site_admin: false,
      },
      html_url: 'https://github.com/TaylorShane/ColYCBillboard.com',
      description: 'Web application to serve club content on displays throughout the club',
      fork: false,
      url: 'https://api.github.com/repos/TaylorShane/ColYCBillboard.com',
      forks_url: 'https://api.github.com/repos/TaylorShane/ColYCBillboard.com/forks',
      keys_url: 'https://api.github.com/repos/TaylorShane/ColYCBillboard.com/keys{/key_id}',
      collaborators_url: 'https://api.github.com/repos/TaylorShane/ColYCBillboard.com/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/TaylorShane/ColYCBillboard.com/teams',
      hooks_url: 'https://api.github.com/repos/TaylorShane/ColYCBillboard.com/hooks',
      issue_events_url: 'https://api.github.com/repos/TaylorShane/ColYCBillboard.com/issues/events{/number}',
      events_url: 'https://api.github.com/repos/TaylorShane/ColYCBillboard.com/events',
      assignees_url: 'https://api.github.com/repos/TaylorShane/ColYCBillboard.com/assignees{/user}',
      branches_url: 'https://api.github.com/repos/TaylorShane/ColYCBillboard.com/branches{/branch}',
      tags_url: 'https://api.github.com/repos/TaylorShane/ColYCBillboard.com/tags',
      blobs_url: 'https://api.github.com/repos/TaylorShane/ColYCBillboard.com/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/TaylorShane/ColYCBillboard.com/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/TaylorShane/ColYCBillboard.com/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/TaylorShane/ColYCBillboard.com/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/TaylorShane/ColYCBillboard.com/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/TaylorShane/ColYCBillboard.com/languages',
      stargazers_url: 'https://api.github.com/repos/TaylorShane/ColYCBillboard.com/stargazers',
      contributors_url: 'https://api.github.com/repos/TaylorShane/ColYCBillboard.com/contributors',
      subscribers_url: 'https://api.github.com/repos/TaylorShane/ColYCBillboard.com/subscribers',
      subscription_url: 'https://api.github.com/repos/TaylorShane/ColYCBillboard.com/subscription',
      commits_url: 'https://api.github.com/repos/TaylorShane/ColYCBillboard.com/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/TaylorShane/ColYCBillboard.com/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/TaylorShane/ColYCBillboard.com/comments{/number}',
      issue_comment_url: 'https://api.github.com/repos/TaylorShane/ColYCBillboard.com/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/TaylorShane/ColYCBillboard.com/contents/{+path}',
      compare_url: 'https://api.github.com/repos/TaylorShane/ColYCBillboard.com/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/TaylorShane/ColYCBillboard.com/merges',
      archive_url: 'https://api.github.com/repos/TaylorShane/ColYCBillboard.com/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/TaylorShane/ColYCBillboard.com/downloads',
      issues_url: 'https://api.github.com/repos/TaylorShane/ColYCBillboard.com/issues{/number}',
      pulls_url: 'https://api.github.com/repos/TaylorShane/ColYCBillboard.com/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/TaylorShane/ColYCBillboard.com/milestones{/number}',
      notifications_url:
        'https://api.github.com/repos/TaylorShane/ColYCBillboard.com/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/TaylorShane/ColYCBillboard.com/labels{/name}',
      releases_url: 'https://api.github.com/repos/TaylorShane/ColYCBillboard.com/releases{/id}',
      deployments_url: 'https://api.github.com/repos/TaylorShane/ColYCBillboard.com/deployments',
      created_at: '2021-11-07T17:01:09Z',
      updated_at: '2021-12-28T21:06:28Z',
      pushed_at: '2022-10-14T21:47:20Z',
      git_url: 'git://github.com/TaylorShane/ColYCBillboard.com.git',
      ssh_url: 'git@github.com:TaylorShane/ColYCBillboard.com.git',
      clone_url: 'https://github.com/TaylorShane/ColYCBillboard.com.git',
      svn_url: 'https://github.com/TaylorShane/ColYCBillboard.com',
      homepage: 'https://taylorshane.github.io/ColYCBillboard.com/#/main',
      size: 104289,
      stargazers_count: 0,
      watchers_count: 0,
      language: 'TypeScript',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: true,
      has_discussions: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 3,
      license: null,
      allow_forking: true,
      is_template: false,
      web_commit_signoff_required: false,
      topics: [],
      visibility: 'public',
      forks: 0,
      open_issues: 3,
      watchers: 0,
      default_branch: 'master',
    },
    {
      id: 496687051,
      node_id: 'R_kgDOHZrXyw',
      name: 'ColYCWeather.com',
      full_name: 'TaylorShane/ColYCWeather.com',
      private: false,
      owner: {
        login: 'TaylorShane',
        id: 26348898,
        node_id: 'MDQ6VXNlcjI2MzQ4ODk4',
        avatar_url: 'https://avatars.githubusercontent.com/u/26348898?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/TaylorShane',
        html_url: 'https://github.com/TaylorShane',
        followers_url: 'https://api.github.com/users/TaylorShane/followers',
        following_url: 'https://api.github.com/users/TaylorShane/following{/other_user}',
        gists_url: 'https://api.github.com/users/TaylorShane/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/TaylorShane/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/TaylorShane/subscriptions',
        organizations_url: 'https://api.github.com/users/TaylorShane/orgs',
        repos_url: 'https://api.github.com/users/TaylorShane/repos',
        events_url: 'https://api.github.com/users/TaylorShane/events{/privacy}',
        received_events_url: 'https://api.github.com/users/TaylorShane/received_events',
        type: 'User',
        site_admin: false,
      },
      html_url: 'https://github.com/TaylorShane/ColYCWeather.com',
      description: 'Weather app for ColYC screens',
      fork: false,
      url: 'https://api.github.com/repos/TaylorShane/ColYCWeather.com',
      forks_url: 'https://api.github.com/repos/TaylorShane/ColYCWeather.com/forks',
      keys_url: 'https://api.github.com/repos/TaylorShane/ColYCWeather.com/keys{/key_id}',
      collaborators_url: 'https://api.github.com/repos/TaylorShane/ColYCWeather.com/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/TaylorShane/ColYCWeather.com/teams',
      hooks_url: 'https://api.github.com/repos/TaylorShane/ColYCWeather.com/hooks',
      issue_events_url: 'https://api.github.com/repos/TaylorShane/ColYCWeather.com/issues/events{/number}',
      events_url: 'https://api.github.com/repos/TaylorShane/ColYCWeather.com/events',
      assignees_url: 'https://api.github.com/repos/TaylorShane/ColYCWeather.com/assignees{/user}',
      branches_url: 'https://api.github.com/repos/TaylorShane/ColYCWeather.com/branches{/branch}',
      tags_url: 'https://api.github.com/repos/TaylorShane/ColYCWeather.com/tags',
      blobs_url: 'https://api.github.com/repos/TaylorShane/ColYCWeather.com/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/TaylorShane/ColYCWeather.com/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/TaylorShane/ColYCWeather.com/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/TaylorShane/ColYCWeather.com/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/TaylorShane/ColYCWeather.com/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/TaylorShane/ColYCWeather.com/languages',
      stargazers_url: 'https://api.github.com/repos/TaylorShane/ColYCWeather.com/stargazers',
      contributors_url: 'https://api.github.com/repos/TaylorShane/ColYCWeather.com/contributors',
      subscribers_url: 'https://api.github.com/repos/TaylorShane/ColYCWeather.com/subscribers',
      subscription_url: 'https://api.github.com/repos/TaylorShane/ColYCWeather.com/subscription',
      commits_url: 'https://api.github.com/repos/TaylorShane/ColYCWeather.com/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/TaylorShane/ColYCWeather.com/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/TaylorShane/ColYCWeather.com/comments{/number}',
      issue_comment_url: 'https://api.github.com/repos/TaylorShane/ColYCWeather.com/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/TaylorShane/ColYCWeather.com/contents/{+path}',
      compare_url: 'https://api.github.com/repos/TaylorShane/ColYCWeather.com/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/TaylorShane/ColYCWeather.com/merges',
      archive_url: 'https://api.github.com/repos/TaylorShane/ColYCWeather.com/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/TaylorShane/ColYCWeather.com/downloads',
      issues_url: 'https://api.github.com/repos/TaylorShane/ColYCWeather.com/issues{/number}',
      pulls_url: 'https://api.github.com/repos/TaylorShane/ColYCWeather.com/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/TaylorShane/ColYCWeather.com/milestones{/number}',
      notifications_url:
        'https://api.github.com/repos/TaylorShane/ColYCWeather.com/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/TaylorShane/ColYCWeather.com/labels{/name}',
      releases_url: 'https://api.github.com/repos/TaylorShane/ColYCWeather.com/releases{/id}',
      deployments_url: 'https://api.github.com/repos/TaylorShane/ColYCWeather.com/deployments',
      created_at: '2022-05-26T16:09:08Z',
      updated_at: '2022-06-29T00:54:30Z',
      pushed_at: '2022-06-29T01:00:48Z',
      git_url: 'git://github.com/TaylorShane/ColYCWeather.com.git',
      ssh_url: 'git@github.com:TaylorShane/ColYCWeather.com.git',
      clone_url: 'https://github.com/TaylorShane/ColYCWeather.com.git',
      svn_url: 'https://github.com/TaylorShane/ColYCWeather.com',
      homepage: 'https://taylorshane.github.io/ColYCBillboard.com/',
      size: 893,
      stargazers_count: 0,
      watchers_count: 0,
      language: 'TypeScript',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: true,
      has_discussions: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 1,
      license: null,
      allow_forking: true,
      is_template: false,
      web_commit_signoff_required: false,
      topics: ['angular'],
      visibility: 'public',
      forks: 0,
      open_issues: 1,
      watchers: 0,
      default_branch: 'master',
    },
    {
      id: 91989845,
      node_id: 'MDEwOlJlcG9zaXRvcnk5MTk4OTg0NQ==',
      name: 'Graphy',
      full_name: 'TaylorShane/Graphy',
      private: false,
      owner: {
        login: 'TaylorShane',
        id: 26348898,
        node_id: 'MDQ6VXNlcjI2MzQ4ODk4',
        avatar_url: 'https://avatars.githubusercontent.com/u/26348898?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/TaylorShane',
        html_url: 'https://github.com/TaylorShane',
        followers_url: 'https://api.github.com/users/TaylorShane/followers',
        following_url: 'https://api.github.com/users/TaylorShane/following{/other_user}',
        gists_url: 'https://api.github.com/users/TaylorShane/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/TaylorShane/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/TaylorShane/subscriptions',
        organizations_url: 'https://api.github.com/users/TaylorShane/orgs',
        repos_url: 'https://api.github.com/users/TaylorShane/repos',
        events_url: 'https://api.github.com/users/TaylorShane/events{/privacy}',
        received_events_url: 'https://api.github.com/users/TaylorShane/received_events',
        type: 'User',
        site_admin: false,
      },
      html_url: 'https://github.com/TaylorShane/Graphy',
      description: 'Educational Android app created to help middle school students learn geometry.',
      fork: false,
      url: 'https://api.github.com/repos/TaylorShane/Graphy',
      forks_url: 'https://api.github.com/repos/TaylorShane/Graphy/forks',
      keys_url: 'https://api.github.com/repos/TaylorShane/Graphy/keys{/key_id}',
      collaborators_url: 'https://api.github.com/repos/TaylorShane/Graphy/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/TaylorShane/Graphy/teams',
      hooks_url: 'https://api.github.com/repos/TaylorShane/Graphy/hooks',
      issue_events_url: 'https://api.github.com/repos/TaylorShane/Graphy/issues/events{/number}',
      events_url: 'https://api.github.com/repos/TaylorShane/Graphy/events',
      assignees_url: 'https://api.github.com/repos/TaylorShane/Graphy/assignees{/user}',
      branches_url: 'https://api.github.com/repos/TaylorShane/Graphy/branches{/branch}',
      tags_url: 'https://api.github.com/repos/TaylorShane/Graphy/tags',
      blobs_url: 'https://api.github.com/repos/TaylorShane/Graphy/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/TaylorShane/Graphy/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/TaylorShane/Graphy/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/TaylorShane/Graphy/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/TaylorShane/Graphy/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/TaylorShane/Graphy/languages',
      stargazers_url: 'https://api.github.com/repos/TaylorShane/Graphy/stargazers',
      contributors_url: 'https://api.github.com/repos/TaylorShane/Graphy/contributors',
      subscribers_url: 'https://api.github.com/repos/TaylorShane/Graphy/subscribers',
      subscription_url: 'https://api.github.com/repos/TaylorShane/Graphy/subscription',
      commits_url: 'https://api.github.com/repos/TaylorShane/Graphy/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/TaylorShane/Graphy/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/TaylorShane/Graphy/comments{/number}',
      issue_comment_url: 'https://api.github.com/repos/TaylorShane/Graphy/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/TaylorShane/Graphy/contents/{+path}',
      compare_url: 'https://api.github.com/repos/TaylorShane/Graphy/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/TaylorShane/Graphy/merges',
      archive_url: 'https://api.github.com/repos/TaylorShane/Graphy/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/TaylorShane/Graphy/downloads',
      issues_url: 'https://api.github.com/repos/TaylorShane/Graphy/issues{/number}',
      pulls_url: 'https://api.github.com/repos/TaylorShane/Graphy/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/TaylorShane/Graphy/milestones{/number}',
      notifications_url: 'https://api.github.com/repos/TaylorShane/Graphy/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/TaylorShane/Graphy/labels{/name}',
      releases_url: 'https://api.github.com/repos/TaylorShane/Graphy/releases{/id}',
      deployments_url: 'https://api.github.com/repos/TaylorShane/Graphy/deployments',
      created_at: '2017-05-21T21:51:30Z',
      updated_at: '2022-07-15T16:56:27Z',
      pushed_at: '2021-02-14T23:28:13Z',
      git_url: 'git://github.com/TaylorShane/Graphy.git',
      ssh_url: 'git@github.com:TaylorShane/Graphy.git',
      clone_url: 'https://github.com/TaylorShane/Graphy.git',
      svn_url: 'https://github.com/TaylorShane/Graphy',
      homepage: '',
      size: 8925,
      stargazers_count: 0,
      watchers_count: 0,
      language: 'Java',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      has_discussions: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: null,
      allow_forking: true,
      is_template: false,
      web_commit_signoff_required: false,
      topics: ['andriod', 'educational', 'geometry'],
      visibility: 'public',
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'master',
    },
    {
      id: 107329991,
      node_id: 'MDEwOlJlcG9zaXRvcnkxMDczMjk5OTE=',
      name: 'Modern-Database-Management',
      full_name: 'TaylorShane/Modern-Database-Management',
      private: false,
      owner: {
        login: 'TaylorShane',
        id: 26348898,
        node_id: 'MDQ6VXNlcjI2MzQ4ODk4',
        avatar_url: 'https://avatars.githubusercontent.com/u/26348898?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/TaylorShane',
        html_url: 'https://github.com/TaylorShane',
        followers_url: 'https://api.github.com/users/TaylorShane/followers',
        following_url: 'https://api.github.com/users/TaylorShane/following{/other_user}',
        gists_url: 'https://api.github.com/users/TaylorShane/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/TaylorShane/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/TaylorShane/subscriptions',
        organizations_url: 'https://api.github.com/users/TaylorShane/orgs',
        repos_url: 'https://api.github.com/users/TaylorShane/repos',
        events_url: 'https://api.github.com/users/TaylorShane/events{/privacy}',
        received_events_url: 'https://api.github.com/users/TaylorShane/received_events',
        type: 'User',
        site_admin: false,
      },
      html_url: 'https://github.com/TaylorShane/Modern-Database-Management',
      description: 'A 3NF relational database.',
      fork: false,
      url: 'https://api.github.com/repos/TaylorShane/Modern-Database-Management',
      forks_url: 'https://api.github.com/repos/TaylorShane/Modern-Database-Management/forks',
      keys_url: 'https://api.github.com/repos/TaylorShane/Modern-Database-Management/keys{/key_id}',
      collaborators_url:
        'https://api.github.com/repos/TaylorShane/Modern-Database-Management/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/TaylorShane/Modern-Database-Management/teams',
      hooks_url: 'https://api.github.com/repos/TaylorShane/Modern-Database-Management/hooks',
      issue_events_url: 'https://api.github.com/repos/TaylorShane/Modern-Database-Management/issues/events{/number}',
      events_url: 'https://api.github.com/repos/TaylorShane/Modern-Database-Management/events',
      assignees_url: 'https://api.github.com/repos/TaylorShane/Modern-Database-Management/assignees{/user}',
      branches_url: 'https://api.github.com/repos/TaylorShane/Modern-Database-Management/branches{/branch}',
      tags_url: 'https://api.github.com/repos/TaylorShane/Modern-Database-Management/tags',
      blobs_url: 'https://api.github.com/repos/TaylorShane/Modern-Database-Management/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/TaylorShane/Modern-Database-Management/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/TaylorShane/Modern-Database-Management/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/TaylorShane/Modern-Database-Management/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/TaylorShane/Modern-Database-Management/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/TaylorShane/Modern-Database-Management/languages',
      stargazers_url: 'https://api.github.com/repos/TaylorShane/Modern-Database-Management/stargazers',
      contributors_url: 'https://api.github.com/repos/TaylorShane/Modern-Database-Management/contributors',
      subscribers_url: 'https://api.github.com/repos/TaylorShane/Modern-Database-Management/subscribers',
      subscription_url: 'https://api.github.com/repos/TaylorShane/Modern-Database-Management/subscription',
      commits_url: 'https://api.github.com/repos/TaylorShane/Modern-Database-Management/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/TaylorShane/Modern-Database-Management/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/TaylorShane/Modern-Database-Management/comments{/number}',
      issue_comment_url: 'https://api.github.com/repos/TaylorShane/Modern-Database-Management/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/TaylorShane/Modern-Database-Management/contents/{+path}',
      compare_url: 'https://api.github.com/repos/TaylorShane/Modern-Database-Management/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/TaylorShane/Modern-Database-Management/merges',
      archive_url: 'https://api.github.com/repos/TaylorShane/Modern-Database-Management/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/TaylorShane/Modern-Database-Management/downloads',
      issues_url: 'https://api.github.com/repos/TaylorShane/Modern-Database-Management/issues{/number}',
      pulls_url: 'https://api.github.com/repos/TaylorShane/Modern-Database-Management/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/TaylorShane/Modern-Database-Management/milestones{/number}',
      notifications_url:
        'https://api.github.com/repos/TaylorShane/Modern-Database-Management/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/TaylorShane/Modern-Database-Management/labels{/name}',
      releases_url: 'https://api.github.com/repos/TaylorShane/Modern-Database-Management/releases{/id}',
      deployments_url: 'https://api.github.com/repos/TaylorShane/Modern-Database-Management/deployments',
      created_at: '2017-10-17T22:17:15Z',
      updated_at: '2020-12-02T00:49:48Z',
      pushed_at: '2020-11-22T23:18:48Z',
      git_url: 'git://github.com/TaylorShane/Modern-Database-Management.git',
      ssh_url: 'git@github.com:TaylorShane/Modern-Database-Management.git',
      clone_url: 'https://github.com/TaylorShane/Modern-Database-Management.git',
      svn_url: 'https://github.com/TaylorShane/Modern-Database-Management',
      homepage: '',
      size: 381,
      stargazers_count: 0,
      watchers_count: 0,
      language: 'PLSQL',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      has_discussions: false,
      forks_count: 1,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: null,
      allow_forking: true,
      is_template: false,
      web_commit_signoff_required: false,
      topics: [],
      visibility: 'public',
      forks: 1,
      open_issues: 0,
      watchers: 0,
      default_branch: 'master',
    },
    {
      id: 433963137,
      node_id: 'R_kgDOGd3AgQ',
      name: 'rpi_ws281x',
      full_name: 'TaylorShane/rpi_ws281x',
      private: false,
      owner: {
        login: 'TaylorShane',
        id: 26348898,
        node_id: 'MDQ6VXNlcjI2MzQ4ODk4',
        avatar_url: 'https://avatars.githubusercontent.com/u/26348898?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/TaylorShane',
        html_url: 'https://github.com/TaylorShane',
        followers_url: 'https://api.github.com/users/TaylorShane/followers',
        following_url: 'https://api.github.com/users/TaylorShane/following{/other_user}',
        gists_url: 'https://api.github.com/users/TaylorShane/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/TaylorShane/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/TaylorShane/subscriptions',
        organizations_url: 'https://api.github.com/users/TaylorShane/orgs',
        repos_url: 'https://api.github.com/users/TaylorShane/repos',
        events_url: 'https://api.github.com/users/TaylorShane/events{/privacy}',
        received_events_url: 'https://api.github.com/users/TaylorShane/received_events',
        type: 'User',
        site_admin: false,
      },
      html_url: 'https://github.com/TaylorShane/rpi_ws281x',
      description: 'Userspace Raspberry Pi PWM library for WS281X LEDs',
      fork: true,
      url: 'https://api.github.com/repos/TaylorShane/rpi_ws281x',
      forks_url: 'https://api.github.com/repos/TaylorShane/rpi_ws281x/forks',
      keys_url: 'https://api.github.com/repos/TaylorShane/rpi_ws281x/keys{/key_id}',
      collaborators_url: 'https://api.github.com/repos/TaylorShane/rpi_ws281x/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/TaylorShane/rpi_ws281x/teams',
      hooks_url: 'https://api.github.com/repos/TaylorShane/rpi_ws281x/hooks',
      issue_events_url: 'https://api.github.com/repos/TaylorShane/rpi_ws281x/issues/events{/number}',
      events_url: 'https://api.github.com/repos/TaylorShane/rpi_ws281x/events',
      assignees_url: 'https://api.github.com/repos/TaylorShane/rpi_ws281x/assignees{/user}',
      branches_url: 'https://api.github.com/repos/TaylorShane/rpi_ws281x/branches{/branch}',
      tags_url: 'https://api.github.com/repos/TaylorShane/rpi_ws281x/tags',
      blobs_url: 'https://api.github.com/repos/TaylorShane/rpi_ws281x/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/TaylorShane/rpi_ws281x/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/TaylorShane/rpi_ws281x/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/TaylorShane/rpi_ws281x/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/TaylorShane/rpi_ws281x/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/TaylorShane/rpi_ws281x/languages',
      stargazers_url: 'https://api.github.com/repos/TaylorShane/rpi_ws281x/stargazers',
      contributors_url: 'https://api.github.com/repos/TaylorShane/rpi_ws281x/contributors',
      subscribers_url: 'https://api.github.com/repos/TaylorShane/rpi_ws281x/subscribers',
      subscription_url: 'https://api.github.com/repos/TaylorShane/rpi_ws281x/subscription',
      commits_url: 'https://api.github.com/repos/TaylorShane/rpi_ws281x/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/TaylorShane/rpi_ws281x/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/TaylorShane/rpi_ws281x/comments{/number}',
      issue_comment_url: 'https://api.github.com/repos/TaylorShane/rpi_ws281x/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/TaylorShane/rpi_ws281x/contents/{+path}',
      compare_url: 'https://api.github.com/repos/TaylorShane/rpi_ws281x/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/TaylorShane/rpi_ws281x/merges',
      archive_url: 'https://api.github.com/repos/TaylorShane/rpi_ws281x/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/TaylorShane/rpi_ws281x/downloads',
      issues_url: 'https://api.github.com/repos/TaylorShane/rpi_ws281x/issues{/number}',
      pulls_url: 'https://api.github.com/repos/TaylorShane/rpi_ws281x/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/TaylorShane/rpi_ws281x/milestones{/number}',
      notifications_url: 'https://api.github.com/repos/TaylorShane/rpi_ws281x/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/TaylorShane/rpi_ws281x/labels{/name}',
      releases_url: 'https://api.github.com/repos/TaylorShane/rpi_ws281x/releases{/id}',
      deployments_url: 'https://api.github.com/repos/TaylorShane/rpi_ws281x/deployments',
      created_at: '2021-12-01T19:45:35Z',
      updated_at: '2021-12-01T20:41:03Z',
      pushed_at: '2021-12-01T20:40:59Z',
      git_url: 'git://github.com/TaylorShane/rpi_ws281x.git',
      ssh_url: 'git@github.com:TaylorShane/rpi_ws281x.git',
      clone_url: 'https://github.com/TaylorShane/rpi_ws281x.git',
      svn_url: 'https://github.com/TaylorShane/rpi_ws281x',
      homepage: null,
      size: 408,
      stargazers_count: 0,
      watchers_count: 0,
      language: 'C',
      has_issues: false,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      has_discussions: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: {
        key: 'bsd-2-clause',
        name: 'BSD 2-Clause "Simplified" License',
        spdx_id: 'BSD-2-Clause',
        url: 'https://api.github.com/licenses/bsd-2-clause',
        node_id: 'MDc6TGljZW5zZTQ=',
      },
      allow_forking: true,
      is_template: false,
      web_commit_signoff_required: false,
      topics: [],
      visibility: 'public',
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'master',
    },
    {
      id: 314845300,
      node_id: 'MDEwOlJlcG9zaXRvcnkzMTQ4NDUzMDA=',
      name: 'shanetaylor.dev',
      full_name: 'TaylorShane/shanetaylor.dev',
      private: false,
      owner: {
        login: 'TaylorShane',
        id: 26348898,
        node_id: 'MDQ6VXNlcjI2MzQ4ODk4',
        avatar_url: 'https://avatars.githubusercontent.com/u/26348898?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/TaylorShane',
        html_url: 'https://github.com/TaylorShane',
        followers_url: 'https://api.github.com/users/TaylorShane/followers',
        following_url: 'https://api.github.com/users/TaylorShane/following{/other_user}',
        gists_url: 'https://api.github.com/users/TaylorShane/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/TaylorShane/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/TaylorShane/subscriptions',
        organizations_url: 'https://api.github.com/users/TaylorShane/orgs',
        repos_url: 'https://api.github.com/users/TaylorShane/repos',
        events_url: 'https://api.github.com/users/TaylorShane/events{/privacy}',
        received_events_url: 'https://api.github.com/users/TaylorShane/received_events',
        type: 'User',
        site_admin: false,
      },
      html_url: 'https://github.com/TaylorShane/shanetaylor.dev',
      description: 'Angular Developer profile website',
      fork: false,
      url: 'https://api.github.com/repos/TaylorShane/shanetaylor.dev',
      forks_url: 'https://api.github.com/repos/TaylorShane/shanetaylor.dev/forks',
      keys_url: 'https://api.github.com/repos/TaylorShane/shanetaylor.dev/keys{/key_id}',
      collaborators_url: 'https://api.github.com/repos/TaylorShane/shanetaylor.dev/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/TaylorShane/shanetaylor.dev/teams',
      hooks_url: 'https://api.github.com/repos/TaylorShane/shanetaylor.dev/hooks',
      issue_events_url: 'https://api.github.com/repos/TaylorShane/shanetaylor.dev/issues/events{/number}',
      events_url: 'https://api.github.com/repos/TaylorShane/shanetaylor.dev/events',
      assignees_url: 'https://api.github.com/repos/TaylorShane/shanetaylor.dev/assignees{/user}',
      branches_url: 'https://api.github.com/repos/TaylorShane/shanetaylor.dev/branches{/branch}',
      tags_url: 'https://api.github.com/repos/TaylorShane/shanetaylor.dev/tags',
      blobs_url: 'https://api.github.com/repos/TaylorShane/shanetaylor.dev/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/TaylorShane/shanetaylor.dev/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/TaylorShane/shanetaylor.dev/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/TaylorShane/shanetaylor.dev/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/TaylorShane/shanetaylor.dev/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/TaylorShane/shanetaylor.dev/languages',
      stargazers_url: 'https://api.github.com/repos/TaylorShane/shanetaylor.dev/stargazers',
      contributors_url: 'https://api.github.com/repos/TaylorShane/shanetaylor.dev/contributors',
      subscribers_url: 'https://api.github.com/repos/TaylorShane/shanetaylor.dev/subscribers',
      subscription_url: 'https://api.github.com/repos/TaylorShane/shanetaylor.dev/subscription',
      commits_url: 'https://api.github.com/repos/TaylorShane/shanetaylor.dev/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/TaylorShane/shanetaylor.dev/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/TaylorShane/shanetaylor.dev/comments{/number}',
      issue_comment_url: 'https://api.github.com/repos/TaylorShane/shanetaylor.dev/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/TaylorShane/shanetaylor.dev/contents/{+path}',
      compare_url: 'https://api.github.com/repos/TaylorShane/shanetaylor.dev/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/TaylorShane/shanetaylor.dev/merges',
      archive_url: 'https://api.github.com/repos/TaylorShane/shanetaylor.dev/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/TaylorShane/shanetaylor.dev/downloads',
      issues_url: 'https://api.github.com/repos/TaylorShane/shanetaylor.dev/issues{/number}',
      pulls_url: 'https://api.github.com/repos/TaylorShane/shanetaylor.dev/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/TaylorShane/shanetaylor.dev/milestones{/number}',
      notifications_url:
        'https://api.github.com/repos/TaylorShane/shanetaylor.dev/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/TaylorShane/shanetaylor.dev/labels{/name}',
      releases_url: 'https://api.github.com/repos/TaylorShane/shanetaylor.dev/releases{/id}',
      deployments_url: 'https://api.github.com/repos/TaylorShane/shanetaylor.dev/deployments',
      created_at: '2020-11-21T15:43:00Z',
      updated_at: '2022-07-15T16:56:16Z',
      pushed_at: '2022-11-27T21:20:18Z',
      git_url: 'git://github.com/TaylorShane/shanetaylor.dev.git',
      ssh_url: 'git@github.com:TaylorShane/shanetaylor.dev.git',
      clone_url: 'https://github.com/TaylorShane/shanetaylor.dev.git',
      svn_url: 'https://github.com/TaylorShane/shanetaylor.dev',
      homepage: 'https://shanetaylor.dev/',
      size: 246194,
      stargazers_count: 0,
      watchers_count: 0,
      language: 'TypeScript',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      has_discussions: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 3,
      license: null,
      allow_forking: true,
      is_template: false,
      web_commit_signoff_required: false,
      topics: [],
      visibility: 'public',
      forks: 0,
      open_issues: 3,
      watchers: 0,
      default_branch: 'master',
    },
    {
      id: 87119342,
      node_id: 'MDEwOlJlcG9zaXRvcnk4NzExOTM0Mg==',
      name: 'Spotter',
      full_name: 'TaylorShane/Spotter',
      private: false,
      owner: {
        login: 'TaylorShane',
        id: 26348898,
        node_id: 'MDQ6VXNlcjI2MzQ4ODk4',
        avatar_url: 'https://avatars.githubusercontent.com/u/26348898?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/TaylorShane',
        html_url: 'https://github.com/TaylorShane',
        followers_url: 'https://api.github.com/users/TaylorShane/followers',
        following_url: 'https://api.github.com/users/TaylorShane/following{/other_user}',
        gists_url: 'https://api.github.com/users/TaylorShane/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/TaylorShane/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/TaylorShane/subscriptions',
        organizations_url: 'https://api.github.com/users/TaylorShane/orgs',
        repos_url: 'https://api.github.com/users/TaylorShane/repos',
        events_url: 'https://api.github.com/users/TaylorShane/events{/privacy}',
        received_events_url: 'https://api.github.com/users/TaylorShane/received_events',
        type: 'User',
        site_admin: false,
      },
      html_url: 'https://github.com/TaylorShane/Spotter',
      description: 'A WPF C# app that tracks caloric intake and exercise management.',
      fork: false,
      url: 'https://api.github.com/repos/TaylorShane/Spotter',
      forks_url: 'https://api.github.com/repos/TaylorShane/Spotter/forks',
      keys_url: 'https://api.github.com/repos/TaylorShane/Spotter/keys{/key_id}',
      collaborators_url: 'https://api.github.com/repos/TaylorShane/Spotter/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/TaylorShane/Spotter/teams',
      hooks_url: 'https://api.github.com/repos/TaylorShane/Spotter/hooks',
      issue_events_url: 'https://api.github.com/repos/TaylorShane/Spotter/issues/events{/number}',
      events_url: 'https://api.github.com/repos/TaylorShane/Spotter/events',
      assignees_url: 'https://api.github.com/repos/TaylorShane/Spotter/assignees{/user}',
      branches_url: 'https://api.github.com/repos/TaylorShane/Spotter/branches{/branch}',
      tags_url: 'https://api.github.com/repos/TaylorShane/Spotter/tags',
      blobs_url: 'https://api.github.com/repos/TaylorShane/Spotter/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/TaylorShane/Spotter/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/TaylorShane/Spotter/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/TaylorShane/Spotter/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/TaylorShane/Spotter/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/TaylorShane/Spotter/languages',
      stargazers_url: 'https://api.github.com/repos/TaylorShane/Spotter/stargazers',
      contributors_url: 'https://api.github.com/repos/TaylorShane/Spotter/contributors',
      subscribers_url: 'https://api.github.com/repos/TaylorShane/Spotter/subscribers',
      subscription_url: 'https://api.github.com/repos/TaylorShane/Spotter/subscription',
      commits_url: 'https://api.github.com/repos/TaylorShane/Spotter/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/TaylorShane/Spotter/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/TaylorShane/Spotter/comments{/number}',
      issue_comment_url: 'https://api.github.com/repos/TaylorShane/Spotter/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/TaylorShane/Spotter/contents/{+path}',
      compare_url: 'https://api.github.com/repos/TaylorShane/Spotter/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/TaylorShane/Spotter/merges',
      archive_url: 'https://api.github.com/repos/TaylorShane/Spotter/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/TaylorShane/Spotter/downloads',
      issues_url: 'https://api.github.com/repos/TaylorShane/Spotter/issues{/number}',
      pulls_url: 'https://api.github.com/repos/TaylorShane/Spotter/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/TaylorShane/Spotter/milestones{/number}',
      notifications_url: 'https://api.github.com/repos/TaylorShane/Spotter/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/TaylorShane/Spotter/labels{/name}',
      releases_url: 'https://api.github.com/repos/TaylorShane/Spotter/releases{/id}',
      deployments_url: 'https://api.github.com/repos/TaylorShane/Spotter/deployments',
      created_at: '2017-04-03T20:47:10Z',
      updated_at: '2021-01-18T02:47:09Z',
      pushed_at: '2021-01-02T21:16:45Z',
      git_url: 'git://github.com/TaylorShane/Spotter.git',
      ssh_url: 'git@github.com:TaylorShane/Spotter.git',
      clone_url: 'https://github.com/TaylorShane/Spotter.git',
      svn_url: 'https://github.com/TaylorShane/Spotter',
      homepage: '',
      size: 20706,
      stargazers_count: 0,
      watchers_count: 0,
      language: 'C#',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      has_discussions: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: null,
      allow_forking: true,
      is_template: false,
      web_commit_signoff_required: false,
      topics: ['csharp', 'diet-managment', 'event-driven', 'wpf-application'],
      visibility: 'public',
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'master',
    },
    {
      id: 339136114,
      node_id: 'MDEwOlJlcG9zaXRvcnkzMzkxMzYxMTQ=',
      name: 'TaylorShane',
      full_name: 'TaylorShane/TaylorShane',
      private: false,
      owner: {
        login: 'TaylorShane',
        id: 26348898,
        node_id: 'MDQ6VXNlcjI2MzQ4ODk4',
        avatar_url: 'https://avatars.githubusercontent.com/u/26348898?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/TaylorShane',
        html_url: 'https://github.com/TaylorShane',
        followers_url: 'https://api.github.com/users/TaylorShane/followers',
        following_url: 'https://api.github.com/users/TaylorShane/following{/other_user}',
        gists_url: 'https://api.github.com/users/TaylorShane/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/TaylorShane/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/TaylorShane/subscriptions',
        organizations_url: 'https://api.github.com/users/TaylorShane/orgs',
        repos_url: 'https://api.github.com/users/TaylorShane/repos',
        events_url: 'https://api.github.com/users/TaylorShane/events{/privacy}',
        received_events_url: 'https://api.github.com/users/TaylorShane/received_events',
        type: 'User',
        site_admin: false,
      },
      html_url: 'https://github.com/TaylorShane/TaylorShane',
      description: 'Config files for my GitHub profile.',
      fork: false,
      url: 'https://api.github.com/repos/TaylorShane/TaylorShane',
      forks_url: 'https://api.github.com/repos/TaylorShane/TaylorShane/forks',
      keys_url: 'https://api.github.com/repos/TaylorShane/TaylorShane/keys{/key_id}',
      collaborators_url: 'https://api.github.com/repos/TaylorShane/TaylorShane/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/TaylorShane/TaylorShane/teams',
      hooks_url: 'https://api.github.com/repos/TaylorShane/TaylorShane/hooks',
      issue_events_url: 'https://api.github.com/repos/TaylorShane/TaylorShane/issues/events{/number}',
      events_url: 'https://api.github.com/repos/TaylorShane/TaylorShane/events',
      assignees_url: 'https://api.github.com/repos/TaylorShane/TaylorShane/assignees{/user}',
      branches_url: 'https://api.github.com/repos/TaylorShane/TaylorShane/branches{/branch}',
      tags_url: 'https://api.github.com/repos/TaylorShane/TaylorShane/tags',
      blobs_url: 'https://api.github.com/repos/TaylorShane/TaylorShane/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/TaylorShane/TaylorShane/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/TaylorShane/TaylorShane/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/TaylorShane/TaylorShane/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/TaylorShane/TaylorShane/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/TaylorShane/TaylorShane/languages',
      stargazers_url: 'https://api.github.com/repos/TaylorShane/TaylorShane/stargazers',
      contributors_url: 'https://api.github.com/repos/TaylorShane/TaylorShane/contributors',
      subscribers_url: 'https://api.github.com/repos/TaylorShane/TaylorShane/subscribers',
      subscription_url: 'https://api.github.com/repos/TaylorShane/TaylorShane/subscription',
      commits_url: 'https://api.github.com/repos/TaylorShane/TaylorShane/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/TaylorShane/TaylorShane/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/TaylorShane/TaylorShane/comments{/number}',
      issue_comment_url: 'https://api.github.com/repos/TaylorShane/TaylorShane/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/TaylorShane/TaylorShane/contents/{+path}',
      compare_url: 'https://api.github.com/repos/TaylorShane/TaylorShane/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/TaylorShane/TaylorShane/merges',
      archive_url: 'https://api.github.com/repos/TaylorShane/TaylorShane/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/TaylorShane/TaylorShane/downloads',
      issues_url: 'https://api.github.com/repos/TaylorShane/TaylorShane/issues{/number}',
      pulls_url: 'https://api.github.com/repos/TaylorShane/TaylorShane/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/TaylorShane/TaylorShane/milestones{/number}',
      notifications_url: 'https://api.github.com/repos/TaylorShane/TaylorShane/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/TaylorShane/TaylorShane/labels{/name}',
      releases_url: 'https://api.github.com/repos/TaylorShane/TaylorShane/releases{/id}',
      deployments_url: 'https://api.github.com/repos/TaylorShane/TaylorShane/deployments',
      created_at: '2021-02-15T16:23:46Z',
      updated_at: '2021-11-10T14:30:32Z',
      pushed_at: '2021-11-10T14:30:30Z',
      git_url: 'git://github.com/TaylorShane/TaylorShane.git',
      ssh_url: 'git@github.com:TaylorShane/TaylorShane.git',
      clone_url: 'https://github.com/TaylorShane/TaylorShane.git',
      svn_url: 'https://github.com/TaylorShane/TaylorShane',
      homepage: 'https://github.com/TaylorShane',
      size: 2,
      stargazers_count: 0,
      watchers_count: 0,
      language: null,
      has_issues: false,
      has_projects: true,
      has_downloads: true,
      has_wiki: false,
      has_pages: false,
      has_discussions: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: null,
      allow_forking: true,
      is_template: false,
      web_commit_signoff_required: false,
      topics: ['config', 'github-config'],
      visibility: 'public',
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'main',
    },
  ];

  public static readonly allBackupLangData: Languages[] = [
    {
      name: 'Modern-Database-Management',
      lang: ['PLSQL'],
      size: [381],
    },
    {
      name: 'Spotter',
      lang: ['C#'],
      size: [63114],
    },
    {
      name: 'graphy',
      lang: ['Java'],
      size: [8925],
    },
    {
      name: 'BrewBuddy-Android',
      lang: ['Java'],
      size: [17960],
    },
    {
      name: 'BrewBuddy-iOS',
      lang: ['Swift'],
      size: [15522],
    },
    {
      name: 'shanetaylor.dev',
      lang: ['TypeScript'],
      size: [246194],
    },
    {
      name: 'ColYCWeather.com',
      lang: ['TypeScript'],
      size: [893],
    },
    {
      name: 'ColYCBillboard.com',
      lang: ['TypeScript'],
      size: [104289],
    },
    {
      name: 'rpi_ws281x',
      lang: ['C'],
      size: [408],
    },
  ];

  public static readonly graphyStaticInfo: ProjectData = {
    id: 'graphy',
    attributes: [
      'Live in Playstore',
      'Responsive Layout',
      'Responsive design',
      'Compatible With 90+% Android',
      'Randomly generated puzzles',
    ],
    blurb:
      'Graphy is an educational Android App designed for common class-room Chrome tablets that I created during a 10-week internship at Northeastern Illinois University. Selected as the Computer Science expert for a mathematics focused group of students and professors, I worked on a National Science Foundation research grant focusing on Computational Thinking and bringing that thinking to younger students. I solely developed and deployed the educational app Graphy to help pre-service teachers teach the fundamentals of Geometry to middle school students while employing Computational Thinking.',
    images: [
      '../../assets/img/graphy/ScreenShots/Screenshot_1500145891.webp',
      '../../assets/img/graphy/ScreenShots/Screenshot_1500145896.webp',
      '../../assets/img/graphy/ScreenShots/Screenshot_1500145900.webp',
      '../../assets/img/graphy/ScreenShots/Screenshot_1500145905.webp',
      '../../assets/img/graphy/ScreenShots/Screenshot_1500149162.webp',
      '../../assets/img/graphy/ScreenShots/Screenshot_1500149174.webp',
    ],
    portrait: false,
    name: 'Graphy',
    playstoreLink: 'https://play.google.com/store/apps/details?id=com.shane_taylor.Graphy',
    repoLink: 'https://github.com/TaylorShane/NEIU2017SummerInternship',
    userGuideLink: '/#/graphy-user-guide',
    privacyLink: '/#/graphy-privacy-terms',
  };

  public static readonly thgStaticInfo: ProjectData = {
    attributes: ['Twitter API integration to curate haiku', 'Responsive design', 'Compatible With 90+% Android'],
    blurb:
      'Trump Haiku Generator creates beautiful and inspirational haiku using words taken directly from the presidents typed and spoken words. Two flavors of haiku are offered. The random button creates a haiku using three random sentences that Donald Trump has spoken. The real displays a haiku that Donald Trump has spoken fully and word for word.',
    images: [
      '../../assets/img/THG/Screenshot_1510861783.webp',
      '../../assets/img/THG/Screenshot_1510861989.webp',
      '../../assets/img/THG/Screenshot_1510861997.webp',
    ],
    portrait: true,
    name: 'Trump Haiku Generator',

    playstoreLink: 'https://play.google.com/store/apps/details?id=com.shane_taylor.trumphaikugenerator&hl=en',

    websiteLink: 'https://trumphaikugenerator.com/',
    privacyLink: 'https://www.trumphaikugenerator.com/#/privacy-terms',
  };

  public static readonly spotterStaticInfo: ProjectData = {
    id: 'Spotter',
    attributes: [
      'XML database',
      'Event driven',
      'Data binding',
      'C# collections',
      '.NET framework',
      'Low coupling',
      'High cohesion',
    ],
    blurb:
      'Spotter is a Windows Presentation Foundation application written in C# and created in Visual Studio. Spotter is a diet and exercise App to help users manage their calorie count, select a workout type, manage their workout schedule, and motivate them to achieve the body type they desire.',
    images: [
      '../../assets/img/spotter/signin_register.webp',
      '../../assets/img/spotter/signin.webp',
      '../../assets/img/spotter/registration.webp',
      '../../assets/img/spotter/meal_calories_total.webp',
      '../../assets/img/spotter/user_profile.webp',
    ],
    portrait: false,
    name: 'Spotter',
    repoLink: 'https://github.com/TaylorShane/Spotter_group',
  };

  public static readonly brewBuddyStaticInfo: ProjectData = {
    id: 'BrewBuddy-Android',
    attributes: ['SQLite Database', 'Listviews', 'Adapters', 'Database Versioning', 'Cursor Adapters'],
    blurb:
      'Brewbuddy is a mobile application built in both Android and iOS versions. It is designed to help the home brewer brew great beers. Brewbuddy has a database of popular    recipes, an ABV calculator, and a bottle calculator so that come    bottling day you know exactly how many bottles to sanitize. You can even add your favorite recipes directly to the home screen for quick access.',
    images: [
      '../../assets/img/brewbuddy/Screenshot_1507672646.webp',
      '../../assets/img/brewbuddy/Screenshot_1507672671.webp',
      '../../assets/img/brewbuddy/Screenshot_1507672664.webp',
    ],
    portrait: true,
    name: 'BrewBuddy',
    repoLink: 'https://github.com/TaylorShane/BrewBuddy-Android',
  };

  public static readonly sweDocStaticInfo: ProjectData = {
    attributes: ['UML Flow Diagrams', 'Entity Relation Diagrams', 'Detailed Actions', 'Post Conditions', 'Validation'],
    blurb:
      'Trained in the methods of Software Engineering and the life cycle of the software development process, I am Agile and Scrum knowledgeable. I understand the necessity of exceptional communication skills and the importance of working your plan and planning your work.',
    images: ['../../assets/img/pixelhero/add.webp', '../../assets/img/pixelhero/srs.webp'],
    portrait: true,
    name: 'Software Engineering Documentation',
    docLinks: [
      'http://www.shane-taylor.com/shane-taylor.com/PixelHeroSRS.html',
      'http://www.shane-taylor.com/shane-taylor.com/PixelHeroADD.html',
    ],
  };

  public static readonly mdbmStaticInfo: ProjectData = {
    id: 'Modern-Database-Management',
    attributes: ['3NF Relational Model', 'Stored Procedures', 'Functions', 'Packages', 'Triggers'],
    blurb:
      'Example complex relational database with Oracle SQL Developer with a script to create the database objects. Which includes the tables and primary/foreign key constraints on those tables, indexes, sequences, views, and PL/SQL stored procedures, functions, packages, and triggers. Also a 3NF relational model, business rules, a data dictionary, ER diagram, and a general description.',
    images: ['../../assets/img/mdbm/mdbm-data-dictionary.webp', '../../assets/img/mdbm/mdbm-er-diagram.webp'],
    portrait: false,
    name: 'SQL Database',
    repoLink: 'https://github.com/TaylorShane/Modern-Database-Management',
  };
}
